# service.yaml
apiVersion: v1
kind: Service
metadata:
    name: helloweb-tls
spec:
    ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
    selector:
        app: helloweb-tls
        tier: web
    type: LoadBalancer