# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb-tls
  labels:
    app: helloweb-tls
  # reloader
  annotations:
    #reloader.stakater.com/auto: "true"
    secret.reloader.stakater.com/reload: "www-tls"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloweb-tls
      tier: web
  template:
    metadata:
      labels:
        app: helloweb-tls
        tier: web
    spec:
      containers:
      - name: helloweb-tls
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app-tls:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        volumeMounts:
          - name: tls
            mountPath: /etc/tls
            readOnly: true
        env:
          - name: dummy-env-name
            value: dummy-env-value
          - name: TLS_CERT
            value: /etc/tls/tls.crt
          - name: TLS_KEY
            value: /etc/tls/tls.key
          - name: TEST_SECRET
            valueFrom:
                secretKeyRef:
                  name: www-tls
                  # from data section of secret: kubectl get secret www-tls -o yaml
                  key: ca.crt

      volumes:
      - name: tls
        secret:
          secretName: www-tls